### ISSUE TITLE
2020 Summer Internship Project: Document Compiling Bitcoin Core for LBTCftCL

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/BlockchainCommonsCommunity#12]
Write Appendix I, "Compiling Bitcoin", for [Learning Bitcoin from the Command Line](https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/blob/master/README.md).

Use a Debian 10 machine, install the full development environment required to compile Bitcoin, pull 0.20 from the GitHub, and compile it. 

Document and explain all the steps.

**Comment by jodobear** [comment]
@shannona I will try to finish it this weeked.

**Comment by shannona** [comment]
Great. Feel free to submit it as a PR to the Learning Bitcoin repo and tag me. My schedule is a little irregular, especially next week, so don't worry if it takes me a few to several days to respond.

**Comment by shannona** [comment]
This is completed and merged. Thanks, @jodobear
